import type { VectorizeParams } from '../lib/vectorize'
import type { AppMobileBindings, MobileBatchState } from './bindings'

/** Source values and stable callbacks used to build memoized mobile bindings. */
export interface MobileBindingsSource {
  theme: AppMobileBindings['theme']
  setTheme: AppMobileBindings['setTheme']
  setAboutOpen: AppMobileBindings['setAboutOpen']
  loadDemoPhotos: AppMobileBindings['loadDemoPhotos']
  isBusy: boolean
  isDragOver: boolean
  photos: AppMobileBindings['photos']
  activePhoto: AppMobileBindings['activePhoto']
  activePhotoId: AppMobileBindings['activePhotoId']
  activeZones: AppMobileBindings['activeZones']
  videoPreviewFaceCount: number
  displayedPhotos: AppMobileBindings['displayedPhotos']
  anonymizedPhotoIds: AppMobileBindings['anonymizedPhotoIds']
  sidebarView: AppMobileBindings['sidebarView']
  selectedForBatch: AppMobileBindings['selectedForBatch']
  setSelectedForBatch: AppMobileBindings['setSelectedForBatch']
  mobileMode: AppMobileBindings['mobileMode']
  setMobileMode: AppMobileBindings['setMobileMode']
  mobilePanel: AppMobileBindings['mobilePanel']
  setMobilePanel: AppMobileBindings['setMobilePanel']
  mobilePanelReturnTo: AppMobileBindings['mobilePanelReturnTo']
  setMobilePanelReturnTo: AppMobileBindings['setMobilePanelReturnTo']
  mobileEditorReturnTo: AppMobileBindings['mobileEditorReturnTo']
  returnToLiveFromEditor: AppMobileBindings['returnToLiveFromEditor']
  galleryBatchSelect: boolean
  setGalleryBatchSelect: AppMobileBindings['setGalleryBatchSelect']
  openUnifiedPicker: AppMobileBindings['openUnifiedPicker']
  openVideoPicker: AppMobileBindings['openVideoPicker']
  selectPhoto: AppMobileBindings['selectPhoto']
  deletePhoto: AppMobileBindings['deletePhoto']
  resetPhotoToOriginal: AppMobileBindings['resetPhotoToOriginal']
  undo: AppMobileBindings['undo']
  undoCount: number
  applyZones: AppMobileBindings['applyZones']
  zonesAnonymized: boolean
  exportActivePhoto: AppMobileBindings['exportActivePhoto']
  exportActiveVideo: AppMobileBindings['exportActiveVideo']
  exportAllLibraryZip: AppMobileBindings['exportAllLibraryZip']
  exportAllLibraryIndividual: AppMobileBindings['exportAllLibraryIndividual']
  videoProcessing: boolean
  videoProgress: AppMobileBindings['videoProgress']
  cancelVideoProcessing: AppMobileBindings['cancelVideoProcessing']
  processActiveVideo: AppMobileBindings['processActiveVideo']
  videoExportFormat: AppMobileBindings['videoExportFormat']
  setVideoExportFormat: AppMobileBindings['setVideoExportFormat']
  videoExportOptions: AppMobileBindings['videoExportOptions']
  videoMaskDrawActive: boolean
  setVideoMaskDrawActive: AppMobileBindings['setVideoMaskDrawActive']
  videoMaskShape: AppMobileBindings['videoMaskShape']
  setVideoMaskShape: AppMobileBindings['setVideoMaskShape']
  imageMaskDrawActive: boolean
  setImageMaskDrawActive: AppMobileBindings['setImageMaskDrawActive']
  videoMaskRangeSec: number
  setVideoMaskRangeSec: AppMobileBindings['setVideoMaskRangeSec']
  stepActiveVideoFrame: AppMobileBindings['stepActiveVideoFrame']
  stepEditFrameAdjacent: AppMobileBindings['stepEditFrameAdjacent']
  openCurrentVideoFrameAsSnapshot: AppMobileBindings['openCurrentVideoFrameAsSnapshot']
  applySnapshotToSourceVideo: AppMobileBindings['applySnapshotToSourceVideo']
  jumpToSourceVideoFromSnapshot: AppMobileBindings['jumpToSourceVideoFromSnapshot']
  sourceVideoPhoto: AppMobileBindings['sourceVideoPhoto']
  activeVideoFrameOverrides: AppMobileBindings['activeVideoFrameOverrides']
  activeVideoTimedZones: AppMobileBindings['activeVideoTimedZones']
  clearVideoTimedZones: AppMobileBindings['clearVideoTimedZones']
  activeVideoTime: number
  activeVideoFrameLabel: AppMobileBindings['activeVideoFrameLabel']
  hasPendingVideoEdits: boolean
  videoPipelineCapabilities: AppMobileBindings['videoPipelineCapabilities']
  exportFormat: AppMobileBindings['exportFormat']
  setExportFormat: AppMobileBindings['setExportFormat']
  exportQuality: number
  setExportQuality: AppMobileBindings['setExportQuality']
  previewFileSizeKb: number | null
  previewRendering: boolean
  activeImageSize: AppMobileBindings['activeImageSize']
  resEditW: number
  resEditH: number
  setResEditW: AppMobileBindings['setResEditW']
  setResEditH: AppMobileBindings['setResEditH']
  resizeWorkCanvas: AppMobileBindings['resizeWorkCanvas']
  mobileExportDraft: AppMobileBindings['mobileExportDraft']
  beginMobileExportEdit: AppMobileBindings['beginMobileExportEdit']
  updateMobileExportDraft: AppMobileBindings['updateMobileExportDraft']
  cancelMobileExportEdit: AppMobileBindings['cancelMobileExportEdit']
  commitMobileExportEdit: AppMobileBindings['commitMobileExportEdit']
  vectorizePanelOpen: boolean
  setVectorizePanelOpen: AppMobileBindings['setVectorizePanelOpen']
  vectorizePreviewActive: boolean
  vectorizeParams: VectorizeParams
  setVectorizeParams: AppMobileBindings['setVectorizeParams']
  updateVectorizeParam: AppMobileBindings['updateVectorizeParam']
  vectorizing: boolean
  svgPreviewSize: number | null
  exportAsSvg: AppMobileBindings['exportAsSvg']
  applyVectorizePreview: AppMobileBindings['applyVectorizePreview']
  brushSize: number
  setBrushSize: AppMobileBindings['setBrushSize']
  brushStrength: number
  setBrushStrength: AppMobileBindings['setBrushStrength']
  toolMode: AppMobileBindings['toolMode']
  setToolMode: AppMobileBindings['setToolMode']
  cropDraft: AppMobileBindings['cropDraft']
  cropToSelection: AppMobileBindings['cropToSelection']
  cancelCropMode: AppMobileBindings['cancelCropMode']
  selectedEffect: AppMobileBindings['selectedEffect']
  setSelectedEffect: AppMobileBindings['setSelectedEffect']
  customImageSource: AppMobileBindings['customImageSource']
  setCustomImageSource: AppMobileBindings['setCustomImageSource']
  asciiCharset: AppMobileBindings['asciiCharset']
  setAsciiCharset: AppMobileBindings['setAsciiCharset']
  customImageAssets: AppMobileBindings['customImageAssets']
  customImagePresetLoading: boolean
  openCustomImagePicker: AppMobileBindings['openCustomImagePicker']
  loadCustomImagePreset: AppMobileBindings['loadCustomImagePreset']
  openEffectPicker: AppMobileBindings['openEffectPicker']
  emojiRandom: boolean
  selectedEmoji: string | null
  onToggleEmojiRandom: AppMobileBindings['onToggleEmojiRandom']
  onPickEmoji: AppMobileBindings['onPickEmoji']
  captureEffectPickerSnapshot: AppMobileBindings['captureEffectPickerSnapshot']
  restoreEffectPickerSnapshot: AppMobileBindings['restoreEffectPickerSnapshot']
  customImageRandom: boolean
  selectedCustomImageId: string | null
  onToggleCustomRandom: AppMobileBindings['onToggleCustomRandom']
  onPickCustomImage: AppMobileBindings['onPickCustomImage']
  liveFixedEmoji: string | null
  liveFixedCustomImageId: string | null
  faceOffset: number
  detectFaceOffset: number
  setDetectFaceOffset: AppMobileBindings['setDetectFaceOffset']
  detectSensitivity: number
  setDetectSensitivity: AppMobileBindings['setDetectSensitivity']
  detectionConfig: AppMobileBindings['detectionConfig']
  setCategoryEnabled: AppMobileBindings['setCategoryEnabled']
  setCategoryThreshold: AppMobileBindings['setCategoryThreshold']
  modelStatus: AppMobileBindings['modelStatus']
  enabledClasses: AppMobileBindings['enabledClasses']
  setEnabledClasses: AppMobileBindings['setEnabledClasses']
  toggleDetectionClass: AppMobileBindings['toggleDetectionClass']
  lastDetectionCounts: AppMobileBindings['lastDetectionCounts']
  showDetectionLabels: boolean
  setShowDetectionLabels: AppMobileBindings['setShowDetectionLabels']
  audioSettings: AppMobileBindings['audioSettings']
  setAudioSettings: AppMobileBindings['setAudioSettings']
  eraserActive: boolean
  autoDetect: boolean
  setAutoDetect: AppMobileBindings['setAutoDetect']
  setShowBoxes: AppMobileBindings['setShowBoxes']
  showBoxes: boolean
  detectFacesOnActiveImage: AppMobileBindings['detectFacesOnActiveImage']
  openDetectSettings: AppMobileBindings['openDetectSettings']
  removeZoneById: AppMobileBindings['removeZoneById']
  removeSelectedZone: AppMobileBindings['removeSelectedZone']
  clearZones: AppMobileBindings['clearZones']
  selectedZoneId: string | null
  categoryIndices: AppMobileBindings['categoryIndices']
  zoneToolCustomized: boolean
  effectToolCustomized: boolean
  setEffectToolCustomized: AppMobileBindings['setEffectToolCustomized']
  setCategoryIndex: AppMobileBindings['setCategoryIndex']
  activeCategory: AppMobileBindings['activeCategory']
  setActiveCategory: AppMobileBindings['setActiveCategory']
  rotateCategoryTool: AppMobileBindings['rotateCategoryTool']
  selectToolCategory: AppMobileBindings['selectToolCategory']
  applyFaceTool: AppMobileBindings['applyFaceTool']
  applyZoneTool: AppMobileBindings['applyZoneTool']
  applyCropTool: AppMobileBindings['applyCropTool']
  applyAdjustTool: AppMobileBindings['applyAdjustTool']
  applyEffectTool: AppMobileBindings['applyEffectTool']
  updateSelectedZoneEffect: AppMobileBindings['updateSelectedZoneEffect']
  mobileViewPan: AppMobileBindings['mobileViewPan']
  setMobileViewPan: AppMobileBindings['setMobileViewPan']
  mobileViewRotation: number
  mobileViewTransformDirty: boolean
  resetMobileViewTransform: AppMobileBindings['resetMobileViewTransform']
  batch: MobileBatchState
  toggleBatchTask: AppMobileBindings['toggleBatchTask']
  toggleExpandBatchTask: AppMobileBindings['toggleExpandBatchTask']
  updateNormalizeSetting: AppMobileBindings['updateNormalizeSetting']
  runNormalizeBatch: AppMobileBindings['runNormalizeBatch']
  exportNormalizeZip: AppMobileBindings['exportNormalizeZip']
  setNormalizeSummary: AppMobileBindings['setNormalizeSummary']
  setColorPreset: AppMobileBindings['setColorPreset']
  setColorAdj: AppMobileBindings['setColorAdj']
  applyColorAdjToActive: AppMobileBindings['applyColorAdjToActive']
  setNotice: AppMobileBindings['setNotice']
  setIsNormalizeCropPicking: AppMobileBindings['setIsNormalizeCropPicking']
  setNormalizeCropDraft: AppMobileBindings['setNormalizeCropDraft']
  isNormalizeCropPicking: boolean
  activeNormalizeCrop: AppMobileBindings['activeNormalizeCrop']
  applyTemplateFromCurrentCrop: AppMobileBindings['applyTemplateFromCurrentCrop']
  detectFrameOnActivePhoto: AppMobileBindings['detectFrameOnActivePhoto']
  detectContentAwareCropOnActivePhoto: AppMobileBindings['detectContentAwareCropOnActivePhoto']
  pointerSessionRef: AppMobileBindings['pointerSessionRef']
  resetDetectorStatus: AppMobileBindings['resetDetectorStatus']
  initializeDetector: AppMobileBindings['initializeDetector']
  setDetector: AppMobileBindings['setDetector']
  liveDetectEnabled: boolean
  setLiveDetectEnabled: AppMobileBindings['setLiveDetectEnabled']
  mobileViewZoom: number
  setMobileViewZoom: AppMobileBindings['setMobileViewZoom']
  lastDetectFailed: boolean
  isDetecting: boolean
  detector: AppMobileBindings['detector']
  detectorLoading: boolean
  modelLoadProgress: AppMobileBindings['modelLoadProgress']
  addLiveMediaToLibrary: AppMobileBindings['addLiveMediaToLibrary']
  openPhotoInEditor: AppMobileBindings['openPhotoInEditor']
  stepAdjacentLibraryPhoto: AppMobileBindings['stepAdjacentLibraryPhoto']
  showMobileToast: AppMobileBindings['showMobileToast']
  exportLibraryProgress: AppMobileBindings['exportLibraryProgress']
  exitLiveToWorkspace: AppMobileBindings['exitLiveToWorkspace']
  stepMobileViewZoom: AppMobileBindings['stepMobileViewZoom']
  adjTransform: AppMobileBindings['adjTransform']
  setAdjTransform: AppMobileBindings['setAdjTransform']
  adjTransformStrength: number
  setAdjTransformStrength: AppMobileBindings['setAdjTransformStrength']
  adjTransformParams: AppMobileBindings['adjTransformParams']
  setAdjParam: AppMobileBindings['setAdjParam']
  adjPixelShiftType: AppMobileBindings['adjPixelShiftType']
  setAdjPixelShiftType: AppMobileBindings['setAdjPixelShiftType']
  commitAdjTransform: AppMobileBindings['commitAdjTransform']
  resetAdjTransformPreview: AppMobileBindings['resetAdjTransformPreview']
  enabledDistorts: AppMobileBindings['enabledDistorts']
  toggleDistortEffect: AppMobileBindings['toggleDistortEffect']
  distortStrengthByEffect: AppMobileBindings['distortStrengthByEffect']
  setDistortStrength: AppMobileBindings['setDistortStrength']
}

export function buildMobileBindings(src: MobileBindingsSource): AppMobileBindings {
  return { ...src }
}
